$(document).ready(function(){
	$('#course').owlCarousel({
		items:3,
		margin:10,
		nav:true,
		dots:false,
		loop:true,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:true
	        },
	        600:{
	            items:3,
	            nav:false
	        },
	        1000:{
	            items:3,
	            nav:true,
	            loop:false
	        }
	    }
	});
	$('#partner').owlCarousel({
		items:4,
		margin:10,
		nav:false,
		dots:false,
		loop:true,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:false
	        },
	        600:{
	            items:3,
	            nav:false
	        },
	        1000:{
	            items:6,
	            nav:false,
	            loop:true
	        }
	    }
	});
});